### ISSUE TITLE
invalid discord invte link

### ISSUE THREAD

**Issue by cow03haha** [luissilva1044894/FlaskPyrezAPI#305]
support server link in readme is invalid

**Comment by luissilva1044894** [comment]
Yo, @cow03haha. I've deleted my support server...

Do you need any help? You can DM me on Discord or Twitch. Or just `@` me here.

**Comment by cow03haha** [comment]
@luissilva1044894 
getLatestPatchNotes is not work, I am not sure if I am using this method correctly
here is my code
```py
from pyrez.api import PaladinsAPI, StatusPageAPI
from pyrez.enumerations.Language import Language

paladins = PaladinsAPI(devId = 'devId', authKey = 'authKey')
data = paladins.getLatestPatchNotes()
print(data)
paladins.close()
```
and here is error
```
$ /usr/bin/python3 /media/cow03/NoobCow_CodeSpace/python/misc/paladins_api.py
Traceback (most recent call last):
  File "/media/cow03/NoobCow_CodeSpace/python/misc/paladins_api.py", line 5, in <module>
    data = paladins.getLatestPatchNotes()
  File "/home/cow03/.local/lib/python3.7/site-packages/pyrez/api/PaladinsAPI.py", line 88, in getLatestPatchNotes
    __ = self.getWebsitePost(language=language or Language.English, slug=PaladinsWebsitePost(**_[0]).slug)
  File "/home/cow03/.local/lib/python3.7/site-packages/pyrez/api/PaladinsAPI.py", line 105, in getWebsitePost
    __ = [ PaladinsWebsitePost(**___) for ___ in (_ or []) ]
  File "/home/cow03/.local/lib/python3.7/site-packages/pyrez/api/PaladinsAPI.py", line 105, in <listcomp>
    __ = [ PaladinsWebsitePost(**___) for ___ in (_ or []) ]
TypeError: type object argument after ** must be a mapping, not str
```

**Comment by luissilva1044894** [comment]
@cow03haha Hey, it's being a while. Sorry for the delay...

My old server was never active and I'm not planning to create a new one. But there one that I'm in. Not mine, but there some Hi-Rez devs too. <https://discord.gg/52Vz34W>

I've commited a fix for your issue, can you check it?
Also, there are some non-public endpoints, such as:

<https://nonsocial.herokuapp.com/api/paladins/patch_notes?lang={LANG}>
<https://nonsocial.herokuapp.com/api/smite/patch_notes?lang={LANG}>

Where `LANG` are the same as supported: `es`, `pt`, `pl` & `en`. Defaults to `en`.
So, free feel to use it.
